### ISSUE TITLE
Google drive link does not work

### ISSUE THREAD

**Issue by MaxGhi8** [PredictiveIntelligenceLab/NOMAD#1]
Hi guys,
I really appreciate the work you have done in the paper "Nonlinear Manifold Decoders for Operator Learning" and I want to play a little bit with your code... I try to download the data with the Google Drive link you provided in the readme, but I get error 403. Can you kindly update the link?

Thanks in advance,
Massimiliano

**Comment by hieronimoDos** [comment]
Hi Massimiliano,

The Google Drive link is updated. You can download all the codes and datasets from there. 

Best,
George

**Comment by MaxGhi8** [comment]
Thank you so much!
